version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: strava-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: strava-leaderboard
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    networks:
      - strava-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

  # Node.js Application - Pull from GitHub Container Registry
  app:
    image: ghcr.io/YOUR_GITHUB_USERNAME/strava-leaderboard:latest
    container_name: strava-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongodb:27017/strava-leaderboard
      - STRAVA_CLIENT_ID=${STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SECRET=${STRAVA_CLIENT_SECRET}
      - STRAVA_REDIRECT_URI=${STRAVA_REDIRECT_URI}
      - SESSION_SECRET=${SESSION_SECRET}
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - strava-network
    volumes:
      - ./logs:/app/logs

networks:
  strava-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
